USE [EdanLibraryDB]
GO
/****** Object:  Table [dbo].[LowPrivilege]    Script Date: 8/4/2021 6:24:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LowPrivilege](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Privilege] [varchar](50) NOT NULL,
 CONSTRAINT [PK_LowPrivilege] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
