USE [EdanLibraryDB]
GO
/****** Object:  Table [dbo].[CheckedOut]    Script Date: 5/12/2021 6:17:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CheckedOut](
	[CheckOutID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_CheckedOut] PRIMARY KEY CLUSTERED 
(
	[CheckOutID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
